#!/bin/sh

set -e

ruby -S bundle exec jekyll build
ruby -S bundle exec htmlproofer ./_site --check-html --check-sri --url-ignore '/fonts.gstatic.com/'
ruby -S bundle exec rubocop -D --config .rubocop.yml
ruby -S bundle exec script/validate-html
ruby -S gem build jekyll-theme-cayman.gemspec
